using Microsoft.AspNetCore.Http;
using Umbraco.Cms.Core.Mapping;
using UrlTracker.Backoffice.UI.Controllers.Models.RedirectImport;
using UrlTracker.Core.Abstractions;
using UrlTracker.Core.Models;

namespace UrlTracker.Backoffice.UI.Map
{
    internal class CsvMap
        : IMapDefinition
    {
        private readonly IUmbracoContextFactoryAbstraction _umbracoContextFactory;

        public CsvMap(IUmbracoContextFactoryAbstraction umbracoContextFactory)
        {
            _umbracoContextFactory = umbracoContextFactory;
        }

        public void DefineMaps(IUmbracoMapper mapper)
        {
            mapper.Define<Redirect, CsvRedirect>(
                (source, context) => new CsvRedirect(),
                Map);

            mapper.Define<CsvRedirect, Redirect>(
                (source, context) => new Redirect(),
                Map);
        }

        private void Map(CsvRedirect source, Redirect target, MapperContext context)
        {
            target.Force = source.Force;
            target.RetainQuery = source.PassThroughQueryString;
            target.Permanent = source.TargetStatusCode == StatusCodes.Status301MovedPermanently;

            if (!string.IsNullOrWhiteSpace(source.SourceUrl))
            {
                target.Source = new UrlSourceStrategy(source.SourceUrl);
            }

            if (!string.IsNullOrWhiteSpace(source.SourceRegex))
            {
                target.Source = new RegexSourceStrategy(source.SourceRegex);
            }

            if (source.TargetNodeId.HasValue)
            {
                using var cref = _umbracoContextFactory.EnsureUmbracoContext();
                var targetcontent = cref.GetContentById(source.TargetNodeId.Value);
                var targetmedia = cref.GetMediaById(source.TargetNodeId.Value);

                if (targetcontent is not null)
                {
                    target.Target = new ContentPageTargetStrategy(targetcontent, source.Culture);
                }
                else if (targetmedia is not null)
                {
                    target.Target = new MediaTargetStrategy(targetmedia);
                }
            }

            if (!string.IsNullOrWhiteSpace(source.TargetUrl))
            {
                target.Target = new UrlTargetStrategy(source.TargetUrl);
            }
        }

        private static void Map(Redirect source, CsvRedirect target, MapperContext context)
        {
            /* NOTE: export does not support redirects by extensions
             * 
             * This mapping device only supports exports using core source and target types.
             * That's because the import and export functions are not to be changed in the initial update.
             * This mapping logic needs to be re-evaluated once the new export feature is built.
             */
            target.Force = source.Force;
            target.PassThroughQueryString = source.RetainQuery;
            target.TargetStatusCode = source.Permanent ? StatusCodes.Status301MovedPermanently : StatusCodes.Status302Found;

            switch (source.Source)
            {
                case UrlSourceStrategy strategy: target.SourceUrl = strategy.Value; break;
                case RegexSourceStrategy strategy: target.SourceRegex = strategy.Value; break;
            }

            /* NOTE: sqewed translations
             * Content redirects no longer rely on a root node. The root node will therefore never be populated.
             * This is only for backwards compatibility with the old import/export model
             * 
             * ALSO NOTE: it is possible that the content no longer exists.
             * rows that are generated by such redirects will cause errors during import.
             * The mapper is not responsible for what makes it into the file
             */
            switch (source.Target)
            {
                case UrlTargetStrategy strategy: target.TargetUrl = strategy.Url; break;
                case ContentPageTargetStrategy strategy: target.TargetNodeId = strategy.Content?.Id; target.Culture = strategy.Culture; break;
                case MediaTargetStrategy strategy: target.TargetNodeId = strategy.Content?.Id; break;
            }
        }
    }
}
