<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Backoffice.Notifications</PackageId>
    <Title>URL Tracker Backoffice Notifications</Title>
    <Description>This package contains notification handlers for the URL Tracker to handle Umbraco content notifications</Description>
    <RootNamespace>UrlTracker.Backoffice.Notifications</RootNamespace>
    <PackageReleaseNotes>1 new feature

- Add support for importing traditional csv formatted files</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Core\UrlTracker.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="16.1.1" />
  </ItemGroup>
</Project>