<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageId>UrlTracker.Backoffice.Notifications</PackageId>
    <Title>URL Tracker Backoffice Notifications</Title>
    <Description>This package contains notification handlers for the URL Tracker to handle Umbraco content notifications</Description>
    <RootNamespace>UrlTracker.Backoffice.Notifications</RootNamespace>
    <PackageReleaseNotes>2 new features, 3 bugfixes, 3 other changes

- Fix failing migration with long URLs
- Fix sorting direction when sorting by URL
- Fix alignment of elements in safari browsers
- Add notifications when creating, updating and deleting redirects
- Add button to all recommendations on landingpage
- Remove image and technical file recommendations from the landingpage
- Remove option to create redirects from image and technical file recommendations
- Common redirects are no longer displayed on the advanced redirect page</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Core\UrlTracker.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="10.6.1" />
  </ItemGroup>
</Project>