<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Backoffice.Notifications</PackageId>
    <Title>URL Tracker Backoffice Notifications</Title>
    <Description>This package contains notification handlers for the URL Tracker to handle Umbraco content notifications</Description>
    <RootNamespace>UrlTracker.Backoffice.Notifications</RootNamespace>
    <PackageReleaseNotes>1 bugfix, 3 other changes

- Fix icon colors on redirect overview
- Replaced custom content picker element with UUI
- Add URL to content preview in Redirect edit panel
- Technical improvements</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Core\UrlTracker.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="14.0.0" />
  </ItemGroup>
</Project>