<Project Sdk="Microsoft.NET.Sdk">
  <!-- Package properties -->
  <PropertyGroup>
    <PackageId>UrlTracker.Web</PackageId>
    <Title>URL Tracker Web</Title>
    <Description>This package contains the web services for the URL Tracker. Useful for package development.</Description>
    <RootNamespace>UrlTracker.Web</RootNamespace>
    <PackageReleaseNotes>7 new features, 1 bugfix, 2 other changes

- Fix database filling up when running for a long time
- New spectacular UI
- New, more intuitive, redirect editing experience
- New presentation for issues: "Not Founds" is replaced with "Recommendations"
- A more clever sorting order for issues
- Standard and advanced redirects are separated into their own area
- Added notifications for developers to listen for changes in redirects
- Statistics for all issues: how often does it occur and where does it originate from?
- Improved performance in the backoffice on larger datasets
- Included the global blocklist extension by default</PackageReleaseNotes>
  </PropertyGroup>
  <!-- END Package properties -->
  <!-- External references -->
  <ItemGroup>
    <PackageReference Include="UAParser" Version="3.1.47" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="13.0.0" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="13.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Core\UrlTracker.Core.csproj" />
  </ItemGroup>
  <!-- END External references -->
  <!-- Exclusions -->
  <ItemGroup>
    <Compile Remove="node_modules\**" />
    <EmbeddedResource Remove="node_modules\**" />
    <None Remove="node_modules\**" />
  </ItemGroup>
  <!-- END Exclusions -->
</Project>