trigger:
  branches:
    include:
    - v10/main
    - v10/develop
    - v10/release/*
    - v10/hotfix
  tags:
    include:
    - 10.*

pool:
  name: Default

parameters:
- name: deployWebsite
  displayName: Deploy website to testing environment
  type: boolean
  default: false

variables:
- group: nuget-package
- group: test-server
- name: BuildConfiguration
  value: 'release'
- name: BuildPlatform
  value: 'any cpu'
- name: Solution
  value: '**\*.sln'
- name: NpmWorkingDirectory
  value: 'src\UrlTracker.Backoffice.UI'
- name: PackageDownloadPatterns
  value: |
    **/*.nupkg
    **/*.snupkg

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build
    steps:
    - checkout: self
      displayName: Clone repository
      fetchDepth: 0
      clean: true

    - task: GitVersion@5
      displayName: GitVersion
      inputs:
        configFilePath: GitVersion.yml
        updateAssemblyInfo: true

    - task: NodeTool@0
      displayName: 'Use node 16.x'
      inputs:
        versionSpec: '16.x'

    - task: Npm@1
      displayName: 'Install front end packages'
      inputs:
        command: 'custom'
        workingDir: $(NpmWorkingDirectory)
        customCommand: 'ci --prefer-offline --no-audit'

    - task: Npm@1
      displayName: 'Build front end'
      inputs:
        command: 'custom'
        workingDir: $(NpmWorkingDirectory)
        customCommand: 'run build:webpack-production'

    - task: UseDotNet@2
      displayName: 'Use .NET 6'
      inputs:
        packageType: 'sdk'
        version: '6.x'

    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: 'UrlTracker.sln'
        arguments: '--configuration $(BuildConfiguration) -p:Version=$(GitVersion.NuGetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: |
          test/UrlTracker.Core.Caching.Memory.Tests/UrlTracker.Core.Caching.Memory.Tests.csproj
          test/UrlTracker.Core.Tests/UrlTracker.Core.Tests.csproj
          test/UrlTracker.IntegrationTests/UrlTracker.IntegrationTests.csproj
          test/UrlTracker.Middleware.Tests/UrlTracker.Middleware.Tests.csproj
          test/UrlTracker.Web.Tests/UrlTracker.Web.Tests.csproj
        arguments: '--configuration $(BuildConfiguration) -p:Version=$(GitVersion.NuGetVersion) --collect "XPlat Code Coverage" --no-build'

    - script: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:$(Agent.WorkFolder)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:Cobertura -assemblyfilters:+UrlTracker.*;-UrlTracker.Resources.*;-UrlTracker.*.Tests
      displayName: Create code coverage report

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage report'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
        reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        arguments: '--configuration $(BuildConfiguration) -p:Version=$(GitVersion.NuGetVersion) --no-build'
        packagesToPack: src/**/*.csproj
        versioningScheme: byEnvVar
        versionEnvVar: GitVersion.NuGetVersion
        verbosityPack: Normal
        packDirectory: '$(Build.ArtifactStagingDirectory)/packages'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish package artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)/packages'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
    - ${{ if eq(parameters.deployWebsite, true) }}:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet build website'
        inputs:
          command: publish
          publishWebProjects: false
          projects: test/**/UrlTracker.Resources.Website.csproj
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/website -p:Version=$(GitVersion.NuGetVersion) --no-build'
      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish website artifacts'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)/website'
          ArtifactName: 'drop-website'
          publishLocation: 'Container'

- stage: dryrun
  displayName: Dry run
  dependsOn: build
  condition: and(succeeded(), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
  jobs:
  - job: download
    displayName: Test download
    workspace:
      clean: all
    steps:
    - checkout: none
    - download: current
      artifact: 'drop'
      patterns: $(PackageDownloadPatterns)
      displayName: Download packages and symbols

- stage: release
  displayName: Release
  dependsOn: build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  variables:
    packageGlob: '$(Pipeline.Workspace)/**/UrlTracker*.nupkg'
    symbolsGlob: '$(Pipeline.Workspace)/**/UrlTracker*.snupkg'
  jobs:
  - job: releaseArtifact
    displayName: Push to artifacts
    workspace:
      clean: all
    steps:
    - checkout: none
    
    - download: current
      artifact: 'drop'
      patterns: $(PackageDownloadPatterns)
      displayName: Download build artifact
    
    - task: DotNetCoreCLI@2
      displayName: 'Push package to artifacts'
      inputs:
        command: push
        publishVstsFeed: '3356baca-d7d8-497c-a5fa-ebd93f79f7c7'
        versioningScheme: byBuildNumber
        packagesToPush: $(packageGlob)
    
    - task: DotNetCoreCLI@2
      displayName: 'Push symbols to artifacts'
      inputs:
        command: push
        publishVstsFeed: '3356baca-d7d8-497c-a5fa-ebd93f79f7c7'
        versioningScheme: byBuildNumber
        packagesToPush: $(symbolsGlob)

  - job: releaseNuget
    displayName: Push to nuget
    workspace:
      clean: all
    steps:
    - checkout: none
    
    - download: current
      patterns: $(PackageDownloadPatterns)
      displayName: Download build artifact
    
    - task: DotNetCoreCLI@2
      displayName: 'push package to nuget.org'
      inputs:
        command: custom
        custom: nuget
        arguments: 'push $(packageGlob) -s https://api.nuget.org/v3/index.json --api-key $(NuGetApiKey)'

- ${{ if eq(parameters.deployWebsite, true) }}:
  - stage: testing
    displayName: Deploy to testing
    dependsOn: build
    condition: succeeded()
    jobs:
    - template: 'azure-pipelines-deploy-iis.yml'
      parameters:
        websiteName: 'urltracker'
        dropFolder: '$(pipeline.workspace)/drop-website/UrlTracker.Resources.Website.zip'
        environment: 'Testing'
        hostName: $(HostName)
        stageName: 'Testing'
        deploymentPath: $(TestPhysicalPath)
        dropName: 'drop-website'