trigger:
  branches:
    include:
    - v9/main
    - v9/develop
    - v9/release/*
    - v9/hotfix
  tags:
    include:
    - 9.*

pool:
  name: Default

variables: 
  BuildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  Solution: '**\*.sln'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        feedsToUse: config
        nugetConfigPath: nuget.config
                
    - task: GitVersion@5
      displayName: GitVersion
      inputs:
        configFilePath: GitVersion.yml
        updateAssemblyInfo: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: src/UrlTracker.Web/UrlTracker.Web.csproj
        arguments: '--configuration $(BuildConfiguration)  /p:Version=$(GitVersion.NuGetVersion)'
        versioningScheme: byBuildNumber

    #- task: DotNetCoreCLI@2
    #  displayName: 'Run tests'
    #  inputs:
    #    command: 'test'
    #    arguments: '.\UrlTracker.sln'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        packagesToPack: src/UrlTracker.Web/UrlTracker.Web.csproj
        nobuild: true
        versioningScheme: byEnvVar
        versionEnvVar: GitVersion.NuGetVersion

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: release
  displayName: Release
  dependsOn: build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  jobs:
  - job: release
    displayName: Push to artifacts
    workspace:
      clean: all
    steps:
    - checkout: none
    
    - download: current
      patterns: '**/*.nupkg'
      displayName: Download build artifact
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet push'
      inputs:
        command: push
        publishVstsFeed: '3356baca-d7d8-497c-a5fa-ebd93f79f7c7'
        versioningScheme: byBuildNumber
        packagesToPush: '$(Pipeline.Workspace)/**/UrlTracker*.nupkg'
