trigger:
  branches:
    include:
    - v9/main
    - v9/develop
    - v9/release/*
    - v9/hotfix
  tags:
    include:
    - 9.*

pool:
  name: Default

variables: 
  BuildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  Solution: '**\*.sln'
  NpmWorkingDirectory: 'src\UrlTracker.Web'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build
    steps:
    - task: GitVersion@5
      displayName: GitVersion
      inputs:
        configFilePath: GitVersion.yml
        updateAssemblyInfo: true

    - task: NodeTool@0
      displayName: 'Use node 16.x'
      inputs:
        versionSpec: '16.x'

    - task: Npm@1
      displayName: 'Install front end packages'
      inputs:
        command: 'custom'
        workingDir: $(NpmWorkingDirectory)
        customCommand: 'ci --prefer-offline --no-audit'

    - task: Npm@1
      displayName: 'Build front end'
      inputs:
        command: 'custom'
        workingDir: $(NpmWorkingDirectory)
        customCommand: 'run build:webpack-production'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: build
        projects: UrlTracker.sln
        arguments: '--configuration $(BuildConfiguration) -p:Version=$(GitVersion.NuGetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: |
          test/UrlTracker.Core.Tests/UrlTracker.Core.Tests.csproj
          test/UrlTracker.Web.Tests/UrlTracker.Web.Tests.csproj
        arguments: '--configuration $(BuildConfiguration) -p:Version=$(GitVersion.NuGetVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        arguments: '--configuration $(BuildConfiguration) -p:Version=$(GitVersion.NuGetVersion)'
        packagesToPack: src/**/*.csproj
        versioningScheme: byEnvVar
        versionEnvVar: GitVersion.NuGetVersion

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: release
  displayName: Release
  dependsOn: build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  variables:
    packageGlob: '$(Pipeline.Workspace)/**/UrlTracker*.nupkg'
  jobs:
  - job: releaseArtifact
    displayName: Push to artifacts
    workspace:
      clean: all
    steps:
    - checkout: none
    
    - download: current
      patterns: '**/*.nupkg'
      displayName: Download build artifact
    
    - task: DotNetCoreCLI@2
      displayName: 'dotnet push'
      inputs:
        command: push
        publishVstsFeed: '3356baca-d7d8-497c-a5fa-ebd93f79f7c7'
        versioningScheme: byBuildNumber
        packagesToPush: $(packageGlob)

  - job: releaseNuget
    displayName: Push to nuget
    workspace:
      clean: all
    steps:
    - checkout: none
    
    - download: current
      patterns: '**/*.nupkg'
      displayName: Download build artifact

    - task: NuGetToolInstaller@1
      displayName: 'install nuget tool'
      inputs:
        versionSpec: 6.x

    - task: NuGetAuthenticate@0
      displayName: 'use nuget service connection'
      inputs:
        nuGetServiceConnections: 'NuGet.org'
    
    - task: NuGetCommand@2
      displayName: 'push to nuget.org'
      inputs:
        command: push
        nuGetFeedType: external
        versioningScheme: byBuildNumber
        packagesToPush: $(packageGlob)