trigger:
  branches:
    include:
    - v8/main
    - v8/develop
    - v8/release/*
    - v8/hotfix
  tags:
    include:
    - 5.*

pool:
  name: Default

variables: 
  BuildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  Solution: '**\UrlTracker.sln'
  NpmWorkingDirectory: 'src\UrlTracker.Frontend'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build
    displayName: Build
    steps:      
    - task: GitVersion@5
      displayName: GitVersion
      inputs:
        configFilePath: GitVersion.yml
        updateAssemblyInfo: true

    - task: NodeTool@0
      displayName: 'Use node 16.x'
      inputs:
        versionSpec: '16.x'

    - task: Npm@1
      displayName: 'Install front end packages'
      inputs:
        command: 'custom'
        workingDir: $(NpmWorkingDirectory)
        customCommand: 'ci --prefer-offline --no-audit'

    - task: Npm@1
      displayName: 'Build front end'
      inputs:
        command: 'custom'
        workingDir: $(NpmWorkingDirectory)
        customCommand: 'run build:webpack-production'
    
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 5.8'
      inputs:
        versionSpec: 5.8

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '$(Solution)'
        feedsToUse: config
        nugetConfigPath: nuget.config

    - task: VSBuild@1
      displayName: 'Build solution **\*.sln'
      inputs:
        solution: '$(Solution)'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'

    - task: VisualStudioTestPlatformInstaller@1
      displayName: 'Install test platform'
      inputs:
        packageFeedSelector: nugetOrg
        versionSelector: latestStable

    - task: VSTest@2
      displayName: 'Run tests'
      inputs:
        testAssemblyVer2: |
         **\$(BuildConfiguration)\*.tests.dll
         !**\obj\**
        codeCoverageEnabled: true
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
        runSettingsFile: '.runsettings'
        vsTestVersion: toolsInstaller

    - task: NuGetCommand@2
      displayName: 'NuGet pack'
      inputs:
        command: pack
        packagesToPack: UrlTracker.nuspec
        packDestination: $(build.artifactstagingdirectory)
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'Gitversion.NuGetVersion'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: release
  displayName: Release
  dependsOn: build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  variables:
    packageGlob: '$(Pipeline.Workspace)/**/UrlTracker*.nupkg'
  jobs:
  - job: releaseArtifact
    displayName: Push to artifacts
    workspace:
      clean: all
    steps:
    - checkout: none
    - download: current
      patterns: '**/*.nupkg'
      displayName: Download build artifact
    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        publishVstsFeed: '3356baca-d7d8-497c-a5fa-ebd93f79f7c7'
        packagesToPush: $(packageGlob)

  - job: releaseNuget
    displayName: Push to nuget
    workspace:
      clean: all
    steps:
    - checkout: none
    - download: current
      patterns: '**/*.nupkg'
      displayName: Download build artifact
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'nuget push $(packageGlob) -ApiKey $(NuGetApiKey) -Source https://api.nuget.org/v3/index.json'