// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetUmbracoManagementApiV1UrlTrackerLandingPageMetricData,
  GetUmbracoManagementApiV1UrlTrackerLandingPageMetricErrors,
  GetUmbracoManagementApiV1UrlTrackerLandingPageMetricResponses,
  GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasData,
  GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasErrors,
  GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasResponses,
  GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryData,
  GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryErrors,
  GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses,
  GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersData,
  GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersErrors,
  GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses,
  GetUmbracoManagementApiV1UrlTrackerRecommendationsData,
  GetUmbracoManagementApiV1UrlTrackerRecommendationsErrors,
  GetUmbracoManagementApiV1UrlTrackerRecommendationsResponses,
  GetUmbracoManagementApiV1UrlTrackerRedirectImportExportData,
  GetUmbracoManagementApiV1UrlTrackerRedirectImportExportErrors,
  GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleData,
  GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleErrors,
  GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleResponses,
  GetUmbracoManagementApiV1UrlTrackerRedirectImportExportResponses,
  GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdData,
  GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdErrors,
  GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses,
  GetUmbracoManagementApiV1UrlTrackerRedirectsData,
  GetUmbracoManagementApiV1UrlTrackerRedirectsErrors,
  GetUmbracoManagementApiV1UrlTrackerRedirectsResponses,
  GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentData,
  GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentErrors,
  GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentResponses,
  GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresData,
  GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresErrors,
  GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresResponses,
  GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersData,
  GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersErrors,
  GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersResponses,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdData,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteData,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteErrors,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteResponses,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdErrors,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdResponses,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkData,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkErrors,
  PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkResponses,
  PostUmbracoManagementApiV1UrlTrackerRedirectImportImportData,
  PostUmbracoManagementApiV1UrlTrackerRedirectImportImportErrors,
  PostUmbracoManagementApiV1UrlTrackerRedirectImportImportResponses,
  PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdData,
  PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteData,
  PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteErrors,
  PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteResponses,
  PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdErrors,
  PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses,
  PostUmbracoManagementApiV1UrlTrackerRedirectsData,
  PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkData,
  PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkErrors,
  PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkResponses,
  PostUmbracoManagementApiV1UrlTrackerRedirectsErrors,
  PostUmbracoManagementApiV1UrlTrackerRedirectsResponses,
  PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkData,
  PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkErrors,
  PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getUmbracoManagementApiV1UrlTrackerLandingPageMetric = <ThrowOnError extends boolean = false>(
  options?: Options<GetUmbracoManagementApiV1UrlTrackerLandingPageMetricData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerLandingPageMetricResponses,
    GetUmbracoManagementApiV1UrlTrackerLandingPageMetricErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/LandingPage/metric',
    ...options,
  });
};

export const getUmbracoManagementApiV1UrlTrackerNotificationsByAlias = <ThrowOnError extends boolean = false>(
  options: Options<GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasResponses,
    GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Notifications/{alias}',
    ...options,
  });
};

export const getUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistory = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses,
    GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/history',
    ...options,
  });
};

export const getUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrers = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersData,
    ThrowOnError
  >,
) => {
  return (options.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses,
    GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/referrers',
    ...options,
  });
};

export const getUmbracoManagementApiV1UrlTrackerRecommendations = <ThrowOnError extends boolean = false>(
  options: Options<GetUmbracoManagementApiV1UrlTrackerRecommendationsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerRecommendationsResponses,
    GetUmbracoManagementApiV1UrlTrackerRecommendationsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Recommendations',
    ...options,
  });
};

export const postUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdResponses,
    PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Recommendations/{recommendationId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const postUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteResponses,
    PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Recommendations/{recommendationId}/delete',
    ...options,
  });
};

export const postUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulk = <ThrowOnError extends boolean = false>(
  options?: Options<PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkResponses,
    PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Recommendations/updatebulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getUmbracoManagementApiV1UrlTrackerScoringRedactionscores = <ThrowOnError extends boolean = false>(
  options?: Options<GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresResponses,
    GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Scoring/redactionscores',
    ...options,
  });
};

export const getUmbracoManagementApiV1UrlTrackerScoringScoreparameters = <ThrowOnError extends boolean = false>(
  options?: Options<GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersResponses,
    GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Scoring/scoreparameters',
    ...options,
  });
};

export const getUmbracoManagementApiV1UrlTrackerRedirectImportExport = <ThrowOnError extends boolean = false>(
  options?: Options<GetUmbracoManagementApiV1UrlTrackerRedirectImportExportData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerRedirectImportExportResponses,
    GetUmbracoManagementApiV1UrlTrackerRedirectImportExportErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/export',
    ...options,
  });
};

export const getUmbracoManagementApiV1UrlTrackerRedirectImportExportexample = <ThrowOnError extends boolean = false>(
  options?: Options<GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleResponses,
    GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/exportexample',
    ...options,
  });
};

export const postUmbracoManagementApiV1UrlTrackerRedirectImportImport = <ThrowOnError extends boolean = false>(
  options?: Options<PostUmbracoManagementApiV1UrlTrackerRedirectImportImportData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRedirectImportImportResponses,
    PostUmbracoManagementApiV1UrlTrackerRedirectImportImportErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/import',
    ...options,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
  });
};

export const getUmbracoManagementApiV1UrlTrackerRedirects = <ThrowOnError extends boolean = false>(
  options: Options<GetUmbracoManagementApiV1UrlTrackerRedirectsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerRedirectsResponses,
    GetUmbracoManagementApiV1UrlTrackerRedirectsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects',
    ...options,
  });
};

export const postUmbracoManagementApiV1UrlTrackerRedirects = <ThrowOnError extends boolean = false>(
  options?: Options<PostUmbracoManagementApiV1UrlTrackerRedirectsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRedirectsResponses,
    PostUmbracoManagementApiV1UrlTrackerRedirectsErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getUmbracoManagementApiV1UrlTrackerRedirectsByRedirectId = <ThrowOnError extends boolean = false>(
  options: Options<GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses,
    GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}',
    ...options,
  });
};

export const postUmbracoManagementApiV1UrlTrackerRedirectsByRedirectId = <ThrowOnError extends boolean = false>(
  options: Options<PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses,
    PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const postUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteResponses,
    PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}/delete',
    ...options,
  });
};

export const postUmbracoManagementApiV1UrlTrackerRedirectsDeletebulk = <ThrowOnError extends boolean = false>(
  options?: Options<PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkResponses,
    PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/deletebulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const postUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulk = <ThrowOnError extends boolean = false>(
  options?: Options<PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkResponses,
    PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/updatebulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
};

export const getUmbracoManagementApiV1UrlTrackerRedirectTargetContent = <ThrowOnError extends boolean = false>(
  options: Options<GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentResponses,
    GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentErrors,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/umbraco/management/api/v1/UrlTracker/RedirectTarget/content',
    ...options,
  });
};
