// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://localhost:44349' | (string & {});
};

export type ContentTargetResponse = {
  icon: string;
  iconColor?: string | null;
  name: string;
  url?: string | null;
};

export type CreateRedirectRequest = {
  source: StrategyViewModel;
  target: StrategyViewModel;
  permanent: boolean;
  retainQuery: boolean;
  force: boolean;
  advanced: boolean;
  key?: string | null;
  solvedRecommendation?: number | null;
};

export type DailyOccurance = {
  occurances: number;
  dateTime: string;
};

export type EntityWithIdRequest1 = {
  id: number;
  data: UpdateRecommendationRequest;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
  message: string;
  category: string;
  type: EventMessageTypeModel;
};

export type NotificationResponse = {
  id: string;
  translatableTitleComponent: string;
  titleArguments: Array<string>;
  translatableBodyComponent: string;
  bodyArguments: Array<string>;
};

export type NumericMetricResponse = {
  value: number;
};

export type RecomendationTrend = 'Unknown' | 'Stable' | 'Increasing' | 'Decreasing';

export type RecommendationCollectionResponse = {
  results: Array<RecommendationResponse>;
  total: number;
};

export type RecommendationHistory = {
  firstOccurance: string;
  lastOccurance: string;
  averagePerDay: number;
  dailyOccurances: Array<DailyOccurance>;
  trend: RecomendationTrend;
};

export type RecommendationOrderBy = 'Importance' | 'MostRecentlyUpdated' | 'Url';

export type RecommendationResponse = {
  id: number;
  ignore: boolean;
  url: string;
  strategy: string;
  variableScore: number;
  updateDate: string;
  createDate: string;
};

export type RedactionScoreResponse = {
  key: string;
  score: number;
};

export type RedirectBulkRequest = {
  id: number;
  data: RedirectRequest;
};

export type RedirectCollectionResponse = {
  results: Array<RedirectResponse>;
  total: number;
};

export type RedirectRequest = {
  source: StrategyViewModel;
  target: StrategyViewModel;
  permanent: boolean;
  retainQuery: boolean;
  force: boolean;
  advanced: boolean;
};

export type RedirectResponse = {
  source: StrategyViewModel;
  target: StrategyViewModel;
  permanent: boolean;
  retainQuery: boolean;
  force: boolean;
  advanced: boolean;
  id: number;
  key: string;
  createDate: string;
  updateDate: string;
  readonly additionalData: {
    [key: string]: unknown;
  };
};

export type RedirectType = 'None' | 'Temporary' | 'Permanent' | 'All';

export type ReferrerResponse = {
  referrerOccurances: number;
  referrerUrl: string;
};

export type ScoreParametersResponse = {
  variableFactor: number;
  redactionFactor: number;
  timeFactor: number;
};

export type StrategyViewModel = {
  strategy: string;
  value: string;
};

export type UpdateRecommendationRequest = {
  recommendationStrategy?: string | null;
  ignore?: boolean | null;
};

export type RedirectResponseWritable = {
  source: StrategyViewModel;
  target: StrategyViewModel;
  permanent: boolean;
  retainQuery: boolean;
  force: boolean;
  advanced: boolean;
  id: number;
  key: string;
  createDate: string;
  updateDate: string;
};

export type GetUmbracoManagementApiV1UrlTrackerLandingPageMetricData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/LandingPage/metric';
};

export type GetUmbracoManagementApiV1UrlTrackerLandingPageMetricErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerLandingPageMetricResponses = {
  /**
   * OK
   */
  200: NumericMetricResponse;
};

export type GetUmbracoManagementApiV1UrlTrackerLandingPageMetricResponse =
  GetUmbracoManagementApiV1UrlTrackerLandingPageMetricResponses[keyof GetUmbracoManagementApiV1UrlTrackerLandingPageMetricResponses];

export type GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasData = {
  body?: never;
  path: {
    alias: string;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Notifications/{alias}';
};

export type GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasResponses = {
  /**
   * OK
   */
  200: Array<NotificationResponse>;
};

export type GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasResponse =
  GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasResponses[keyof GetUmbracoManagementApiV1UrlTrackerNotificationsByAliasResponses];

export type GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryData = {
  body?: never;
  path: {
    recommendationId: number;
  };
  query?: {
    pastDays?: number;
  };
  url: '/umbraco/management/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/history';
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses = {
  /**
   * OK
   */
  200: RecommendationHistory;
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponse =
  GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses[keyof GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses];

export type GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersData = {
  body?: never;
  path: {
    recommendationId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/referrers';
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses = {
  /**
   * OK
   */
  200: Array<ReferrerResponse>;
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponse =
  GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses[keyof GetUmbracoManagementApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses];

export type GetUmbracoManagementApiV1UrlTrackerRecommendationsData = {
  body?: never;
  path?: never;
  query: {
    Query?: string;
    Types?: Array<string>;
    OrderBy?: RecommendationOrderBy;
    Desc?: boolean;
    Page: number;
    PageSize: number;
  };
  url: '/umbraco/management/api/v1/UrlTracker/Recommendations';
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationsErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationsResponses = {
  /**
   * OK
   */
  200: RecommendationCollectionResponse;
};

export type GetUmbracoManagementApiV1UrlTrackerRecommendationsResponse =
  GetUmbracoManagementApiV1UrlTrackerRecommendationsResponses[keyof GetUmbracoManagementApiV1UrlTrackerRecommendationsResponses];

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdData = {
  body?: UpdateRecommendationRequest;
  path: {
    recommendationId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Recommendations/{recommendationId}';
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdResponses = {
  /**
   * OK
   */
  200: RecommendationResponse;
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdResponse =
  PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdResponses[keyof PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdResponses];

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteData = {
  body?: never;
  path: {
    recommendationId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Recommendations/{recommendationId}/delete';
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteResponses = {
  /**
   * OK
   */
  200: RecommendationResponse;
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteResponse =
  PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteResponses[keyof PostUmbracoManagementApiV1UrlTrackerRecommendationsByRecommendationIdDeleteResponses];

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkData = {
  body?: Array<EntityWithIdRequest1>;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Recommendations/updatebulk';
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkResponses = {
  /**
   * OK
   */
  200: RecommendationResponse;
};

export type PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkResponse =
  PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkResponses[keyof PostUmbracoManagementApiV1UrlTrackerRecommendationsUpdatebulkResponses];

export type GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Scoring/redactionscores';
};

export type GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresResponses = {
  /**
   * OK
   */
  200: Array<RedactionScoreResponse>;
};

export type GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresResponse =
  GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresResponses[keyof GetUmbracoManagementApiV1UrlTrackerScoringRedactionscoresResponses];

export type GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Scoring/scoreparameters';
};

export type GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersResponses = {
  /**
   * OK
   */
  200: ScoreParametersResponse;
};

export type GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersResponse =
  GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersResponses[keyof GetUmbracoManagementApiV1UrlTrackerScoringScoreparametersResponses];

export type GetUmbracoManagementApiV1UrlTrackerRedirectImportExportData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/export';
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectImportExportErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectImportExportResponses = {
  /**
   * OK
   */
  200: Blob | File;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectImportExportResponse =
  GetUmbracoManagementApiV1UrlTrackerRedirectImportExportResponses[keyof GetUmbracoManagementApiV1UrlTrackerRedirectImportExportResponses];

export type GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/exportexample';
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleResponses = {
  /**
   * OK
   */
  200: Blob | File;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleResponse =
  GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleResponses[keyof GetUmbracoManagementApiV1UrlTrackerRedirectImportExportexampleResponses];

export type PostUmbracoManagementApiV1UrlTrackerRedirectImportImportData = {
  body?: {
    Redirects: Blob | File;
  };
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/import';
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectImportImportErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectImportImportResponses = {
  /**
   * OK
   */
  200: number;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectImportImportResponse =
  PostUmbracoManagementApiV1UrlTrackerRedirectImportImportResponses[keyof PostUmbracoManagementApiV1UrlTrackerRedirectImportImportResponses];

export type GetUmbracoManagementApiV1UrlTrackerRedirectsData = {
  body?: never;
  path?: never;
  query: {
    Query?: string;
    Advanced?: boolean;
    Types?: Array<RedirectType>;
    SourceTypes?: Array<string>;
    Page: number;
    PageSize: number;
  };
  url: '/umbraco/management/api/v1/UrlTracker/Redirects';
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectsErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectsResponses = {
  /**
   * OK
   */
  200: RedirectCollectionResponse;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectsResponse =
  GetUmbracoManagementApiV1UrlTrackerRedirectsResponses[keyof GetUmbracoManagementApiV1UrlTrackerRedirectsResponses];

export type PostUmbracoManagementApiV1UrlTrackerRedirectsData = {
  body?: CreateRedirectRequest;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects';
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsResponses = {
  /**
   * OK
   */
  200: RedirectResponse;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsResponse =
  PostUmbracoManagementApiV1UrlTrackerRedirectsResponses[keyof PostUmbracoManagementApiV1UrlTrackerRedirectsResponses];

export type GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdData = {
  body?: never;
  path: {
    redirectId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}';
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses = {
  /**
   * OK
   */
  200: RedirectResponse;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponse =
  GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses[keyof GetUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses];

export type PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdData = {
  body?: RedirectRequest;
  path: {
    redirectId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}';
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses = {
  /**
   * OK
   */
  200: RedirectResponse;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponse =
  PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses[keyof PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdResponses];

export type PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteData = {
  body?: never;
  path: {
    redirectId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}/delete';
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteResponses = {
  /**
   * OK
   */
  200: RedirectResponse;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteResponse =
  PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteResponses[keyof PostUmbracoManagementApiV1UrlTrackerRedirectsByRedirectIdDeleteResponses];

export type PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkData = {
  body?: Array<number>;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/deletebulk';
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkResponse =
  PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkResponses[keyof PostUmbracoManagementApiV1UrlTrackerRedirectsDeletebulkResponses];

export type PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkData = {
  body?: Array<RedirectBulkRequest>;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/updatebulk';
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkResponses = {
  /**
   * OK
   */
  200: Array<RedirectResponse>;
};

export type PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkResponse =
  PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkResponses[keyof PostUmbracoManagementApiV1UrlTrackerRedirectsUpdatebulkResponses];

export type GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentData = {
  body?: never;
  path?: never;
  query: {
    Id: string;
    Culture?: string;
  };
  url: '/umbraco/management/api/v1/UrlTracker/RedirectTarget/content';
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentResponses = {
  /**
   * OK
   */
  200: ContentTargetResponse;
};

export type GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentResponse =
  GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentResponses[keyof GetUmbracoManagementApiV1UrlTrackerRedirectTargetContentResponses];
