<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Modules</PackageId>
    <Title>URL Tracker Module registration</Title>
    <Description>This package contains objects for module registration. It keeps helps keeping track of installed modules for the URL Tracker</Description>
    <RootNamespace>UrlTracker.Modules</RootNamespace>
    <PackageReleaseNotes>1 change

- Update to Umbraco 16</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.8" />
  </ItemGroup>
</Project>