<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Modules</PackageId>
    <Title>URL Tracker Module registration</Title>
    <Description>This package contains objects for module registration. It keeps helps keeping track of installed modules for the URL Tracker</Description>
    <RootNamespace>UrlTracker.Modules</RootNamespace>
    <PackageReleaseNotes>4 new features, 1 bugfix, 3 other changes

- Fix untranslated text on the content picker in the redirect edit panel
- Add create date to the redirects on the overview
- Add the date of the first and last occurrance of a recommendation
- Add global deny list package as default plugin
- Disable the redirect source condition while solving a recommendation
- Remove company logo
- Include more technical words for recognition
- The label above the top recommendations now matches the displayed amount</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
  </ItemGroup>
</Project>