<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.GlobalBlocklist</PackageId>
    <Title>UrlTracker Global Block List</Title>
    <Description>The global block list provides an extra filter for the URL Tracker that retrieves a global list from GitHub and adds it as a filter.</Description>
    <RootNamespace>UrlTracker.GlobalBlocklist</RootNamespace>
    <PackageReleaseNotes>1 new feature

- Add support for importing traditional csv formatted files</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Polly" Version="8.4.0" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="13.0.0" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="13.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Modules\UrlTracker.Modules.csproj" />
    <ProjectReference Include="..\UrlTracker.Web\UrlTracker.Web.csproj" />
  </ItemGroup>
</Project>