<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.GlobalBlocklist</PackageId>
    <Title>UrlTracker Global Block List</Title>
    <Description>The global block list provides an extra filter for the URL Tracker that retrieves a global list from GitHub and adds it as a filter.</Description>
    <RootNamespace>UrlTracker.GlobalBlocklist</RootNamespace>
    <PackageReleaseNotes>7 new features, 1 bugfix, 2 other changes

- Fix database filling up when running for a long time
- New spectacular UI
- New, more intuitive, redirect editing experience
- New presentation for issues: "Not Founds" is replaced with "Recommendations"
- A more clever sorting order for issues
- Standard and advanced redirects are separated into their own area
- Added notifications for developers to listen for changes in redirects
- Statistics for all issues: how often does it occur and where does it originate from?
- Improved performance in the backoffice on larger datasets
- Included the global blocklist extension by default</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Polly" Version="8.4.0" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="13.0.0" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="13.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Modules\UrlTracker.Modules.csproj" />
    <ProjectReference Include="..\UrlTracker.Web\UrlTracker.Web.csproj" />
  </ItemGroup>
</Project>