<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Core.Caching.Memory</PackageId>
    <Title>URL Tracker Core Memory Cache</Title>
    <Description>This package contains an in-memory cache layer for the core services of the URL Tracker</Description>
    <RootNamespace>UrlTracker.Core.Caching.Memory</RootNamespace>
    <PackageReleaseNotes>4 new features, 1 bugfix, 3 other changes

- Fix untranslated text on the content picker in the redirect edit panel
- Add create date to the redirects on the overview
- Add the date of the first and last occurrance of a recommendation
- Add global deny list package as default plugin
- Disable the redirect source condition while solving a recommendation
- Remove company logo
- Include more technical words for recognition
- The label above the top recommendations now matches the displayed amount</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Core" Version="10.6.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="6.0.1" />
    <PackageReference Include="Scrutor" Version="4.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Core\UrlTracker.Core.csproj" />
  </ItemGroup>
</Project>