<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Core.Caching.Memory</PackageId>
    <Title>URL Tracker Core Memory Cache</Title>
    <Description>This package contains an in-memory cache layer for the core services of the URL Tracker</Description>
    <RootNamespace>UrlTracker.Core.Caching.Memory</RootNamespace>
    <PackageReleaseNotes>7 new features, 1 bugfix, 2 other changes

- Fix database filling up when running for a long time
- New spectacular UI
- New, more intuitive, redirect editing experience
- New presentation for issues: "Not Founds" is replaced with "Recommendations"
- A more clever sorting order for issues
- Standard and advanced redirects are separated into their own area
- Added notifications for developers to listen for changes in redirects
- Statistics for all issues: how often does it occur and where does it originate from?
- Improved performance in the backoffice on larger datasets
- Included the global blocklist extension by default</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Core" Version="13.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.0" />
    <PackageReference Include="Scrutor" Version="4.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Core\UrlTracker.Core.csproj" />
  </ItemGroup>
</Project>