// This file is auto-generated by @hey-api/openapi-ts

export const $ContentTargetResponse = {
  required: ['icon', 'name'],
  type: 'object',
  properties: {
    icon: {
      type: 'string',
    },
    iconColor: {
      type: 'string',
      nullable: true,
    },
    name: {
      type: 'string',
    },
    url: {
      type: 'string',
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const $CreateRedirectRequest = {
  required: ['force', 'permanent', 'retainQuery', 'source', 'target'],
  type: 'object',
  properties: {
    source: {
      oneOf: [
        {
          $ref: '#/components/schemas/StrategyViewModel',
        },
      ],
    },
    target: {
      oneOf: [
        {
          $ref: '#/components/schemas/StrategyViewModel',
        },
      ],
    },
    permanent: {
      type: 'boolean',
    },
    retainQuery: {
      type: 'boolean',
    },
    force: {
      type: 'boolean',
    },
    key: {
      type: 'string',
      format: 'uuid',
      nullable: true,
    },
    solvedRecommendation: {
      type: 'integer',
      format: 'int32',
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;

export const $DailyOccurance = {
  required: ['dateTime', 'occurances'],
  type: 'object',
  properties: {
    occurances: {
      type: 'integer',
      format: 'int32',
    },
    dateTime: {
      type: 'string',
      format: 'date-time',
    },
  },
  additionalProperties: false,
} as const;

export const $EntityWithIdRequest_1 = {
  required: ['data', 'id'],
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int32',
    },
    data: {
      oneOf: [
        {
          $ref: '#/components/schemas/UpdateRecommendationRequest',
        },
      ],
    },
  },
  additionalProperties: false,
} as const;

export const $EventMessageTypeModel = {
  enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
  type: 'string',
} as const;

export const $NotificationHeaderModel = {
  required: ['category', 'message', 'type'],
  type: 'object',
  properties: {
    message: {
      type: 'string',
    },
    category: {
      type: 'string',
    },
    type: {
      $ref: '#/components/schemas/EventMessageTypeModel',
    },
  },
  additionalProperties: false,
} as const;

export const $NotificationResponse = {
  required: ['bodyArguments', 'id', 'titleArguments', 'translatableBodyComponent', 'translatableTitleComponent'],
  type: 'object',
  properties: {
    id: {
      type: 'string',
    },
    translatableTitleComponent: {
      type: 'string',
    },
    titleArguments: {
      type: 'array',
      items: {
        type: 'string',
      },
    },
    translatableBodyComponent: {
      type: 'string',
    },
    bodyArguments: {
      type: 'array',
      items: {
        type: 'string',
      },
    },
  },
  additionalProperties: false,
} as const;

export const $NumericMetricResponse = {
  required: ['value'],
  type: 'object',
  properties: {
    value: {
      type: 'integer',
      format: 'int32',
    },
  },
  additionalProperties: false,
} as const;

export const $RecomendationTrend = {
  enum: ['Unknown', 'Stable', 'Increasing', 'Decreasing'],
  type: 'string',
} as const;

export const $RecommendationCollectionResponse = {
  required: ['results', 'total'],
  type: 'object',
  properties: {
    results: {
      type: 'array',
      items: {
        oneOf: [
          {
            $ref: '#/components/schemas/RecommendationResponse',
          },
        ],
      },
    },
    total: {
      type: 'integer',
      format: 'int64',
    },
  },
  additionalProperties: false,
} as const;

export const $RecommendationHistory = {
  required: ['averagePerDay', 'dailyOccurances', 'firstOccurance', 'lastOccurance', 'trend'],
  type: 'object',
  properties: {
    firstOccurance: {
      type: 'string',
      format: 'date-time',
    },
    lastOccurance: {
      type: 'string',
      format: 'date-time',
    },
    averagePerDay: {
      type: 'number',
      format: 'double',
    },
    dailyOccurances: {
      type: 'array',
      items: {
        oneOf: [
          {
            $ref: '#/components/schemas/DailyOccurance',
          },
        ],
      },
    },
    trend: {
      $ref: '#/components/schemas/RecomendationTrend',
    },
  },
  additionalProperties: false,
} as const;

export const $RecommendationOrderBy = {
  enum: ['Importance', 'MostRecentlyUpdated', 'Url'],
  type: 'string',
} as const;

export const $RecommendationResponse = {
  required: ['id', 'ignore', 'strategy', 'updateDate', 'url', 'variableScore'],
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int32',
    },
    ignore: {
      type: 'boolean',
    },
    url: {
      type: 'string',
    },
    strategy: {
      type: 'string',
      format: 'uuid',
    },
    variableScore: {
      type: 'integer',
      format: 'int32',
    },
    updateDate: {
      type: 'string',
      format: 'date-time',
    },
  },
  additionalProperties: false,
} as const;

export const $RedactionScoreResponse = {
  required: ['key', 'score'],
  type: 'object',
  properties: {
    key: {
      type: 'string',
      format: 'uuid',
    },
    score: {
      type: 'number',
      format: 'double',
    },
  },
  additionalProperties: false,
} as const;

export const $RedirectBulkRequest = {
  required: ['data', 'id'],
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int32',
    },
    data: {
      oneOf: [
        {
          $ref: '#/components/schemas/RedirectRequest',
        },
      ],
    },
  },
  additionalProperties: false,
} as const;

export const $RedirectCollectionResponse = {
  required: ['results', 'total'],
  type: 'object',
  properties: {
    results: {
      type: 'array',
      items: {
        oneOf: [
          {
            $ref: '#/components/schemas/RedirectResponse',
          },
        ],
      },
    },
    total: {
      type: 'integer',
      format: 'int64',
    },
  },
  additionalProperties: false,
} as const;

export const $RedirectRequest = {
  required: ['force', 'permanent', 'retainQuery', 'source', 'target'],
  type: 'object',
  properties: {
    source: {
      oneOf: [
        {
          $ref: '#/components/schemas/StrategyViewModel',
        },
      ],
    },
    target: {
      oneOf: [
        {
          $ref: '#/components/schemas/StrategyViewModel',
        },
      ],
    },
    permanent: {
      type: 'boolean',
    },
    retainQuery: {
      type: 'boolean',
    },
    force: {
      type: 'boolean',
    },
  },
  additionalProperties: false,
} as const;

export const $RedirectResponse = {
  required: [
    'additionalData',
    'createDate',
    'force',
    'id',
    'key',
    'permanent',
    'retainQuery',
    'source',
    'target',
    'updateDate',
  ],
  type: 'object',
  properties: {
    source: {
      oneOf: [
        {
          $ref: '#/components/schemas/StrategyViewModel',
        },
      ],
    },
    target: {
      oneOf: [
        {
          $ref: '#/components/schemas/StrategyViewModel',
        },
      ],
    },
    permanent: {
      type: 'boolean',
    },
    retainQuery: {
      type: 'boolean',
    },
    force: {
      type: 'boolean',
    },
    id: {
      type: 'integer',
      format: 'int32',
    },
    key: {
      type: 'string',
      format: 'uuid',
    },
    createDate: {
      type: 'string',
      format: 'date-time',
    },
    updateDate: {
      type: 'string',
      format: 'date-time',
    },
    additionalData: {
      type: 'object',
      additionalProperties: {},
      readOnly: true,
    },
  },
  additionalProperties: false,
} as const;

export const $RedirectType = {
  enum: ['None', 'Temporary', 'Permanent', 'All'],
  type: 'string',
} as const;

export const $ReferrerResponse = {
  required: ['referrerOccurances', 'referrerUrl'],
  type: 'object',
  properties: {
    referrerOccurances: {
      type: 'integer',
      format: 'int32',
    },
    referrerUrl: {
      type: 'string',
    },
  },
  additionalProperties: false,
} as const;

export const $ScoreParametersResponse = {
  required: ['redactionFactor', 'timeFactor', 'variableFactor'],
  type: 'object',
  properties: {
    variableFactor: {
      type: 'number',
      format: 'double',
    },
    redactionFactor: {
      type: 'number',
      format: 'double',
    },
    timeFactor: {
      type: 'number',
      format: 'double',
    },
  },
  additionalProperties: false,
} as const;

export const $StrategyViewModel = {
  required: ['strategy', 'value'],
  type: 'object',
  properties: {
    strategy: {
      type: 'string',
      format: 'uuid',
    },
    value: {
      minLength: 1,
      type: 'string',
    },
  },
  additionalProperties: false,
} as const;

export const $UpdateRecommendationRequest = {
  type: 'object',
  properties: {
    recommendationStrategy: {
      type: 'string',
      format: 'uuid',
      nullable: true,
    },
    ignore: {
      type: 'boolean',
      nullable: true,
    },
  },
  additionalProperties: false,
} as const;
