// This file is auto-generated by @hey-api/openapi-ts

export type ContentTargetResponse = {
    icon: string;
    iconColor?: string | null;
    name: string;
    url?: string | null;
};

export type CreateRedirectRequest = {
    source: StrategyViewModel;
    target: StrategyViewModel;
    permanent: boolean;
    retainQuery: boolean;
    force: boolean;
    key?: string | null;
    solvedRecommendation?: number | null;
};

export type DailyOccurance = {
    occurances: number;
    dateTime: Date;
};

export type EntityWithIdRequest_1 = {
    id: number;
    data: UpdateRecommendationRequest;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type NotificationResponse = {
    id: string;
    translatableTitleComponent: string;
    titleArguments: Array<(string)>;
    translatableBodyComponent: string;
    bodyArguments: Array<(string)>;
};

export type NumericMetricResponse = {
    value: number;
};

export enum RecomendationTrend {
    UNKNOWN = 'Unknown',
    STABLE = 'Stable',
    INCREASING = 'Increasing',
    DECREASING = 'Decreasing'
}

export type RecommendationCollectionResponse = {
    results: Array<(RecommendationResponse)>;
    total: number;
};

export type RecommendationHistory = {
    firstOccurance: Date;
    lastOccurance: Date;
    averagePerDay: number;
    dailyOccurances: Array<(DailyOccurance)>;
    trend: RecomendationTrend;
};

export enum RecommendationOrderBy {
    IMPORTANCE = 'Importance',
    MOST_RECENTLY_UPDATED = 'MostRecentlyUpdated',
    URL = 'Url'
}

export type RecommendationResponse = {
    id: number;
    ignore: boolean;
    url: string;
    strategy: string;
    variableScore: number;
    updateDate: Date;
};

export type RedactionScoreResponse = {
    key: string;
    score: number;
};

export type RedirectBulkRequest = {
    id: number;
    data: RedirectRequest;
};

export type RedirectCollectionResponse = {
    results: Array<(RedirectResponse)>;
    total: number;
};

export type RedirectRequest = {
    source: StrategyViewModel;
    target: StrategyViewModel;
    permanent: boolean;
    retainQuery: boolean;
    force: boolean;
};

export type RedirectResponse = {
    source: StrategyViewModel;
    target: StrategyViewModel;
    permanent: boolean;
    retainQuery: boolean;
    force: boolean;
    id: number;
    key: string;
    createDate: Date;
    updateDate: Date;
    readonly additionalData: {
        [key: string]: unknown;
    };
};

export type RedirectStrategyResponse = {
    name: string;
    key: string;
};

export enum RedirectType {
    NONE = 'None',
    TEMPORARY = 'Temporary',
    PERMANENT = 'Permanent',
    ALL = 'All'
}

export type ReferrerResponse = {
    referrerOccurances: number;
    referrerUrl: string;
};

export type ScoreParametersResponse = {
    variableFactor: number;
    redactionFactor: number;
    timeFactor: number;
};

export type StrategyViewModel = {
    strategy: string;
    value: string;
};

export type UpdateRecommendationRequest = {
    recommendationStrategy?: string | null;
    ignore?: boolean | null;
};

export type GetApiV1UrlTrackerLandingPageMetricResponse = NumericMetricResponse;

export type GetApiV1UrlTrackerNotificationsByAliasData = {
    alias: string;
};

export type GetApiV1UrlTrackerNotificationsByAliasResponse = Array<(NotificationResponse)>;

export type GetApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryData = {
    pastDays?: number;
    recommendationId: number;
};

export type GetApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponse = RecommendationHistory;

export type GetApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersData = {
    recommendationId: number;
};

export type GetApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponse = Array<(ReferrerResponse)>;

export type GetApiV1UrlTrackerRecommendationsData = {
    desc?: boolean;
    orderBy?: RecommendationOrderBy;
    page: number;
    pageSize: number;
    query?: string;
    types?: Array<(string)>;
};

export type GetApiV1UrlTrackerRecommendationsResponse = RecommendationCollectionResponse;

export type PostApiV1UrlTrackerRecommendationsByRecommendationIdData = {
    recommendationId: number;
    requestBody?: UpdateRecommendationRequest;
};

export type PostApiV1UrlTrackerRecommendationsByRecommendationIdResponse = RecommendationResponse;

export type PostApiV1UrlTrackerRecommendationsByRecommendationIdDeleteData = {
    recommendationId: number;
};

export type PostApiV1UrlTrackerRecommendationsByRecommendationIdDeleteResponse = RecommendationResponse;

export type PostApiV1UrlTrackerRecommendationsUpdatebulkData = {
    requestBody?: Array<(EntityWithIdRequest_1)>;
};

export type PostApiV1UrlTrackerRecommendationsUpdatebulkResponse = Array<(RecommendationResponse)>;

export type GetApiV1UrlTrackerRedirectImportExportResponse = (Blob | File);

export type GetApiV1UrlTrackerRedirectImportExportexampleResponse = (Blob | File);

export type PostApiV1UrlTrackerRedirectImportImportData = {
    formData?: {
        Redirects: (Blob | File);
    };
};

export type PostApiV1UrlTrackerRedirectImportImportResponse = number;

export type GetApiV1UrlTrackerRedirectStrategyContentData = {
    culture?: string;
    id: string;
};

export type GetApiV1UrlTrackerRedirectStrategyContentResponse = ContentTargetResponse;

export type GetApiV1UrlTrackerRedirectStrategySourcesResponse = Array<(RedirectStrategyResponse)>;

export type GetApiV1UrlTrackerRedirectStrategyTargetsResponse = Array<(RedirectStrategyResponse)>;

export type PostApiV1UrlTrackerRedirectsData = {
    requestBody?: CreateRedirectRequest;
};

export type PostApiV1UrlTrackerRedirectsResponse = RedirectResponse;

export type GetApiV1UrlTrackerRedirectsData = {
    page: number;
    pageSize: number;
    query?: string;
    sourceTypes?: Array<(string)>;
    types?: Array<RedirectType>;
};

export type GetApiV1UrlTrackerRedirectsResponse = RedirectCollectionResponse;

export type GetApiV1UrlTrackerRedirectsByRedirectIdData = {
    redirectId: number;
};

export type GetApiV1UrlTrackerRedirectsByRedirectIdResponse = RedirectResponse;

export type PostApiV1UrlTrackerRedirectsByRedirectIdData = {
    redirectId: number;
    requestBody?: RedirectRequest;
};

export type PostApiV1UrlTrackerRedirectsByRedirectIdResponse = RedirectResponse;

export type PostApiV1UrlTrackerRedirectsByRedirectIdDeleteData = {
    redirectId: number;
};

export type PostApiV1UrlTrackerRedirectsByRedirectIdDeleteResponse = RedirectResponse;

export type PostApiV1UrlTrackerRedirectsDeletebulkData = {
    requestBody?: Array<(number)>;
};

export type PostApiV1UrlTrackerRedirectsDeletebulkResponse = string;

export type PostApiV1UrlTrackerRedirectsUpdatebulkData = {
    requestBody?: Array<(RedirectBulkRequest)>;
};

export type PostApiV1UrlTrackerRedirectsUpdatebulkResponse = Array<(RedirectResponse)>;

export type GetApiV1UrlTrackerScoringRedactionscoresResponse = Array<(RedactionScoreResponse)>;

export type GetApiV1UrlTrackerScoringScoreparametersResponse = ScoreParametersResponse;

export type $OpenApiTs = {
    '/api/v1/UrlTracker/LandingPage/metric': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: NumericMetricResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/Notifications/{alias}': {
        get: {
            req: GetApiV1UrlTrackerNotificationsByAliasData;
            res: {
                /**
                 * OK
                 */
                200: Array<(NotificationResponse)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/history': {
        get: {
            req: GetApiV1UrlTrackerRecommendationAnalysisByRecommendationIdHistoryData;
            res: {
                /**
                 * OK
                 */
                200: RecommendationHistory;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/referrers': {
        get: {
            req: GetApiV1UrlTrackerRecommendationAnalysisByRecommendationIdReferrersData;
            res: {
                /**
                 * OK
                 */
                200: Array<(ReferrerResponse)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/Recommendations': {
        get: {
            req: GetApiV1UrlTrackerRecommendationsData;
            res: {
                /**
                 * OK
                 */
                200: RecommendationCollectionResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/Recommendations/{recommendationId}': {
        post: {
            req: PostApiV1UrlTrackerRecommendationsByRecommendationIdData;
            res: {
                /**
                 * OK
                 */
                200: RecommendationResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: string;
            };
        };
    };
    '/api/v1/UrlTracker/Recommendations/{recommendationId}/delete': {
        post: {
            req: PostApiV1UrlTrackerRecommendationsByRecommendationIdDeleteData;
            res: {
                /**
                 * OK
                 */
                200: RecommendationResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: string;
            };
        };
    };
    '/api/v1/UrlTracker/Recommendations/updatebulk': {
        post: {
            req: PostApiV1UrlTrackerRecommendationsUpdatebulkData;
            res: {
                /**
                 * OK
                 */
                200: Array<(RecommendationResponse)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: string;
            };
        };
    };
    '/api/v1/UrlTracker/RedirectImport/export': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: (Blob | File);
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/RedirectImport/exportexample': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: (Blob | File);
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/RedirectImport/import': {
        post: {
            req: PostApiV1UrlTrackerRedirectImportImportData;
            res: {
                /**
                 * OK
                 */
                200: number;
                /**
                 * Bad Request
                 */
                400: string;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/RedirectStrategy/content': {
        get: {
            req: GetApiV1UrlTrackerRedirectStrategyContentData;
            res: {
                /**
                 * OK
                 */
                200: ContentTargetResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/RedirectStrategy/sources': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<(RedirectStrategyResponse)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/RedirectStrategy/targets': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<(RedirectStrategyResponse)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/Redirects': {
        post: {
            req: PostApiV1UrlTrackerRedirectsData;
            res: {
                /**
                 * OK
                 */
                200: RedirectResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
        get: {
            req: GetApiV1UrlTrackerRedirectsData;
            res: {
                /**
                 * OK
                 */
                200: RedirectCollectionResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/Redirects/{redirectId}': {
        get: {
            req: GetApiV1UrlTrackerRedirectsByRedirectIdData;
            res: {
                /**
                 * OK
                 */
                200: RedirectResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: unknown;
            };
        };
        post: {
            req: PostApiV1UrlTrackerRedirectsByRedirectIdData;
            res: {
                /**
                 * OK
                 */
                200: RedirectResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: string;
            };
        };
    };
    '/api/v1/UrlTracker/Redirects/{redirectId}/delete': {
        post: {
            req: PostApiV1UrlTrackerRedirectsByRedirectIdDeleteData;
            res: {
                /**
                 * OK
                 */
                200: RedirectResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: string;
            };
        };
    };
    '/api/v1/UrlTracker/Redirects/deletebulk': {
        post: {
            req: PostApiV1UrlTrackerRedirectsDeletebulkData;
            res: {
                /**
                 * No Content
                 */
                204: string;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: string;
            };
        };
    };
    '/api/v1/UrlTracker/Redirects/updatebulk': {
        post: {
            req: PostApiV1UrlTrackerRedirectsUpdatebulkData;
            res: {
                /**
                 * OK
                 */
                200: Array<(RedirectResponse)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
                /**
                 * Not Found
                 */
                404: string;
            };
        };
    };
    '/api/v1/UrlTracker/Scoring/redactionscores': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: Array<(RedactionScoreResponse)>;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
    '/api/v1/UrlTracker/Scoring/scoreparameters': {
        get: {
            res: {
                /**
                 * OK
                 */
                200: ScoreParametersResponse;
                /**
                 * The resource is protected and requires an authentication token
                 */
                401: unknown;
            };
        };
    };
};