<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Core</PackageId>
    <Title>URL Tracker Core</Title>
    <Description>This package contains the core services for the URL Tracker. Useful for package development.</Description>
    <RootNamespace>UrlTracker.Core</RootNamespace>
    <PackageReleaseNotes>2 new features, 3 bugfixes, 3 other changes

- Fix failing migration with long URLs
- Fix sorting direction when sorting by URL
- Fix alignment of elements in safari browsers
- Add notifications when creating, updating and deleting redirects
- Add button to all recommendations on landingpage
- Remove image and technical file recommendations from the landingpage
- Remove option to create redirects from image and technical file recommendations
- Common redirects are no longer displayed on the advanced redirect page</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="13.0.0" />
    <PackageReference Include="Scrutor" Version="4.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Modules\UrlTracker.Modules.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="UrlTracker.Core.Tests" />
    <InternalsVisibleTo Include="UrlTracker.IntegrationTests" />
  </ItemGroup>
</Project>