<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Core</PackageId>
    <Title>URL Tracker Core</Title>
    <Description>This package contains the core services for the URL Tracker. Useful for package development.</Description>
    <RootNamespace>UrlTracker.Core</RootNamespace>
    <PackageReleaseNotes>7 new features, 1 bugfix, 2 other changes

- Fix database filling up when running for a long time
- New spectacular UI
- New, more intuitive, redirect editing experience
- New presentation for issues: "Not Founds" is replaced with "Recommendations"
- A more clever sorting order for issues
- Standard and advanced redirects are separated into their own area
- Added notifications for developers to listen for changes in redirects
- Statistics for all issues: how often does it occur and where does it originate from?
- Improved performance in the backoffice on larger datasets
- Included the global blocklist extension by default</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Infrastructure" Version="13.0.0" />
    <PackageReference Include="Scrutor" Version="4.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Modules\UrlTracker.Modules.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="UrlTracker.Core.Tests" />
    <InternalsVisibleTo Include="UrlTracker.IntegrationTests" />
  </ItemGroup>
</Project>