// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client';
import { client } from './client.gen';
import type {
  GetUrlTrackerLandingPageMetricData,
  GetUrlTrackerLandingPageMetricErrors,
  GetUrlTrackerLandingPageMetricResponses,
  GetUrlTrackerNotificationsByAliasData,
  GetUrlTrackerNotificationsByAliasErrors,
  GetUrlTrackerNotificationsByAliasResponses,
  GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryData,
  GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryErrors,
  GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses,
  GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersData,
  GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersErrors,
  GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses,
  GetUrlTrackerRecommendationsData,
  GetUrlTrackerRecommendationsErrors,
  GetUrlTrackerRecommendationsResponses,
  GetUrlTrackerRedirectImportExportData,
  GetUrlTrackerRedirectImportExportErrors,
  GetUrlTrackerRedirectImportExportexampleData,
  GetUrlTrackerRedirectImportExportexampleErrors,
  GetUrlTrackerRedirectImportExportexampleResponses,
  GetUrlTrackerRedirectImportExportResponses,
  GetUrlTrackerRedirectsByRedirectIdData,
  GetUrlTrackerRedirectsByRedirectIdErrors,
  GetUrlTrackerRedirectsByRedirectIdResponses,
  GetUrlTrackerRedirectsData,
  GetUrlTrackerRedirectsErrors,
  GetUrlTrackerRedirectsResponses,
  GetUrlTrackerRedirectTargetContentData,
  GetUrlTrackerRedirectTargetContentErrors,
  GetUrlTrackerRedirectTargetContentResponses,
  GetUrlTrackerScoringRedactionscoresData,
  GetUrlTrackerScoringRedactionscoresErrors,
  GetUrlTrackerScoringRedactionscoresResponses,
  GetUrlTrackerScoringScoreparametersData,
  GetUrlTrackerScoringScoreparametersErrors,
  GetUrlTrackerScoringScoreparametersResponses,
  PostUrlTrackerRecommendationsByRecommendationIdData,
  PostUrlTrackerRecommendationsByRecommendationIdDeleteData,
  PostUrlTrackerRecommendationsByRecommendationIdDeleteErrors,
  PostUrlTrackerRecommendationsByRecommendationIdDeleteResponses,
  PostUrlTrackerRecommendationsByRecommendationIdErrors,
  PostUrlTrackerRecommendationsByRecommendationIdResponses,
  PostUrlTrackerRecommendationsUpdatebulkData,
  PostUrlTrackerRecommendationsUpdatebulkErrors,
  PostUrlTrackerRecommendationsUpdatebulkResponses,
  PostUrlTrackerRedirectImportImportData,
  PostUrlTrackerRedirectImportImportErrors,
  PostUrlTrackerRedirectImportImportResponses,
  PostUrlTrackerRedirectsByRedirectIdData,
  PostUrlTrackerRedirectsByRedirectIdDeleteData,
  PostUrlTrackerRedirectsByRedirectIdDeleteErrors,
  PostUrlTrackerRedirectsByRedirectIdDeleteResponses,
  PostUrlTrackerRedirectsByRedirectIdErrors,
  PostUrlTrackerRedirectsByRedirectIdResponses,
  PostUrlTrackerRedirectsData,
  PostUrlTrackerRedirectsDeletebulkData,
  PostUrlTrackerRedirectsDeletebulkErrors,
  PostUrlTrackerRedirectsDeletebulkResponses,
  PostUrlTrackerRedirectsErrors,
  PostUrlTrackerRedirectsResponses,
  PostUrlTrackerRedirectsUpdatebulkData,
  PostUrlTrackerRedirectsUpdatebulkErrors,
  PostUrlTrackerRedirectsUpdatebulkResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getUrlTrackerLandingPageMetric = <ThrowOnError extends boolean = false>(
  options?: Options<GetUrlTrackerLandingPageMetricData, ThrowOnError>,
): RequestResult<GetUrlTrackerLandingPageMetricResponses, GetUrlTrackerLandingPageMetricErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetUrlTrackerLandingPageMetricResponses,
    GetUrlTrackerLandingPageMetricErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/LandingPage/metric',
    ...options,
  });

export const getUrlTrackerNotificationsByAlias = <ThrowOnError extends boolean = false>(
  options: Options<GetUrlTrackerNotificationsByAliasData, ThrowOnError>,
): RequestResult<GetUrlTrackerNotificationsByAliasResponses, GetUrlTrackerNotificationsByAliasErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUrlTrackerNotificationsByAliasResponses,
    GetUrlTrackerNotificationsByAliasErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Notifications/{alias}',
    ...options,
  });

export const getUrlTrackerRecommendationAnalysisByRecommendationIdHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryData, ThrowOnError>,
): RequestResult<
  GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses,
  GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses,
    GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/history',
    ...options,
  });

export const getUrlTrackerRecommendationAnalysisByRecommendationIdReferrers = <ThrowOnError extends boolean = false>(
  options: Options<GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersData, ThrowOnError>,
): RequestResult<
  GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses,
  GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses,
    GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/referrers',
    ...options,
  });

export const getUrlTrackerRecommendations = <ThrowOnError extends boolean = false>(
  options?: Options<GetUrlTrackerRecommendationsData, ThrowOnError>,
): RequestResult<GetUrlTrackerRecommendationsResponses, GetUrlTrackerRecommendationsErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetUrlTrackerRecommendationsResponses,
    GetUrlTrackerRecommendationsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Recommendations',
    ...options,
  });

export const postUrlTrackerRecommendationsByRecommendationId = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRecommendationsByRecommendationIdData, ThrowOnError>,
): RequestResult<
  PostUrlTrackerRecommendationsByRecommendationIdResponses,
  PostUrlTrackerRecommendationsByRecommendationIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostUrlTrackerRecommendationsByRecommendationIdResponses,
    PostUrlTrackerRecommendationsByRecommendationIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Recommendations/{recommendationId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const postUrlTrackerRecommendationsByRecommendationIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRecommendationsByRecommendationIdDeleteData, ThrowOnError>,
): RequestResult<
  PostUrlTrackerRecommendationsByRecommendationIdDeleteResponses,
  PostUrlTrackerRecommendationsByRecommendationIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostUrlTrackerRecommendationsByRecommendationIdDeleteResponses,
    PostUrlTrackerRecommendationsByRecommendationIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Recommendations/{recommendationId}/delete',
    ...options,
  });

export const postUrlTrackerRecommendationsUpdatebulk = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRecommendationsUpdatebulkData, ThrowOnError>,
): RequestResult<
  PostUrlTrackerRecommendationsUpdatebulkResponses,
  PostUrlTrackerRecommendationsUpdatebulkErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostUrlTrackerRecommendationsUpdatebulkResponses,
    PostUrlTrackerRecommendationsUpdatebulkErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Recommendations/updatebulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getUrlTrackerScoringRedactionscores = <ThrowOnError extends boolean = false>(
  options?: Options<GetUrlTrackerScoringRedactionscoresData, ThrowOnError>,
): RequestResult<
  GetUrlTrackerScoringRedactionscoresResponses,
  GetUrlTrackerScoringRedactionscoresErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetUrlTrackerScoringRedactionscoresResponses,
    GetUrlTrackerScoringRedactionscoresErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Scoring/redactionscores',
    ...options,
  });

export const getUrlTrackerScoringScoreparameters = <ThrowOnError extends boolean = false>(
  options?: Options<GetUrlTrackerScoringScoreparametersData, ThrowOnError>,
): RequestResult<
  GetUrlTrackerScoringScoreparametersResponses,
  GetUrlTrackerScoringScoreparametersErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetUrlTrackerScoringScoreparametersResponses,
    GetUrlTrackerScoringScoreparametersErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Scoring/scoreparameters',
    ...options,
  });

export const getUrlTrackerRedirectImportExport = <ThrowOnError extends boolean = false>(
  options?: Options<GetUrlTrackerRedirectImportExportData, ThrowOnError>,
): RequestResult<GetUrlTrackerRedirectImportExportResponses, GetUrlTrackerRedirectImportExportErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetUrlTrackerRedirectImportExportResponses,
    GetUrlTrackerRedirectImportExportErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/export',
    ...options,
  });

export const getUrlTrackerRedirectImportExportexample = <ThrowOnError extends boolean = false>(
  options?: Options<GetUrlTrackerRedirectImportExportexampleData, ThrowOnError>,
): RequestResult<
  GetUrlTrackerRedirectImportExportexampleResponses,
  GetUrlTrackerRedirectImportExportexampleErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetUrlTrackerRedirectImportExportexampleResponses,
    GetUrlTrackerRedirectImportExportexampleErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/exportexample',
    ...options,
  });

export const postUrlTrackerRedirectImportImport = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRedirectImportImportData, ThrowOnError>,
): RequestResult<PostUrlTrackerRedirectImportImportResponses, PostUrlTrackerRedirectImportImportErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostUrlTrackerRedirectImportImportResponses,
    PostUrlTrackerRedirectImportImportErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/import',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  });

export const getUrlTrackerRedirects = <ThrowOnError extends boolean = false>(
  options?: Options<GetUrlTrackerRedirectsData, ThrowOnError>,
): RequestResult<GetUrlTrackerRedirectsResponses, GetUrlTrackerRedirectsErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetUrlTrackerRedirectsResponses, GetUrlTrackerRedirectsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects',
    ...options,
  });

export const postUrlTrackerRedirects = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRedirectsData, ThrowOnError>,
): RequestResult<PostUrlTrackerRedirectsResponses, PostUrlTrackerRedirectsErrors, ThrowOnError> =>
  (options.client ?? client).post<PostUrlTrackerRedirectsResponses, PostUrlTrackerRedirectsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getUrlTrackerRedirectsByRedirectId = <ThrowOnError extends boolean = false>(
  options: Options<GetUrlTrackerRedirectsByRedirectIdData, ThrowOnError>,
): RequestResult<GetUrlTrackerRedirectsByRedirectIdResponses, GetUrlTrackerRedirectsByRedirectIdErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetUrlTrackerRedirectsByRedirectIdResponses,
    GetUrlTrackerRedirectsByRedirectIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}',
    ...options,
  });

export const postUrlTrackerRedirectsByRedirectId = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRedirectsByRedirectIdData, ThrowOnError>,
): RequestResult<
  PostUrlTrackerRedirectsByRedirectIdResponses,
  PostUrlTrackerRedirectsByRedirectIdErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostUrlTrackerRedirectsByRedirectIdResponses,
    PostUrlTrackerRedirectsByRedirectIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const postUrlTrackerRedirectsByRedirectIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRedirectsByRedirectIdDeleteData, ThrowOnError>,
): RequestResult<
  PostUrlTrackerRedirectsByRedirectIdDeleteResponses,
  PostUrlTrackerRedirectsByRedirectIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    PostUrlTrackerRedirectsByRedirectIdDeleteResponses,
    PostUrlTrackerRedirectsByRedirectIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}/delete',
    ...options,
  });

export const postUrlTrackerRedirectsDeletebulk = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRedirectsDeletebulkData, ThrowOnError>,
): RequestResult<PostUrlTrackerRedirectsDeletebulkResponses, PostUrlTrackerRedirectsDeletebulkErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostUrlTrackerRedirectsDeletebulkResponses,
    PostUrlTrackerRedirectsDeletebulkErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/deletebulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const postUrlTrackerRedirectsUpdatebulk = <ThrowOnError extends boolean = false>(
  options: Options<PostUrlTrackerRedirectsUpdatebulkData, ThrowOnError>,
): RequestResult<PostUrlTrackerRedirectsUpdatebulkResponses, PostUrlTrackerRedirectsUpdatebulkErrors, ThrowOnError> =>
  (options.client ?? client).post<
    PostUrlTrackerRedirectsUpdatebulkResponses,
    PostUrlTrackerRedirectsUpdatebulkErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/Redirects/updatebulk',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getUrlTrackerRedirectTargetContent = <ThrowOnError extends boolean = false>(
  options?: Options<GetUrlTrackerRedirectTargetContentData, ThrowOnError>,
): RequestResult<GetUrlTrackerRedirectTargetContentResponses, GetUrlTrackerRedirectTargetContentErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    GetUrlTrackerRedirectTargetContentResponses,
    GetUrlTrackerRedirectTargetContentErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/management/api/v1/UrlTracker/RedirectTarget/content',
    ...options,
  });
