// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://localhost:44349/' | (string & {});
};

export type ContentTargetResponse = {
  icon: string;
  iconColor: null | string;
  name: string;
  url: null | string;
};

export type CreateRedirectRequest = {
  key?: null | string;
  solvedRecommendation?: null | number;
  source: StrategyViewModel;
  target: StrategyViewModel;
  permanent: boolean;
  retainQuery: boolean;
  force: boolean;
  advanced: boolean;
};

export type DailyOccurance = {
  occurances: number;
  dateTime: string;
};

export type EntityTagHeaderValue = {
  tag: StringSegment;
  isWeak: boolean;
};

export type EntityWithIdRequestOfUpdateRecommendationRequest = {
  id: number;
  data: null | UpdateRecommendationRequest;
};

export type FileStreamResult = {
  fileStream: Stream;
  contentType: null | string;
  fileDownloadName: null | string;
  lastModified?: null | string;
  entityTag?: null | EntityTagHeaderValue;
  enableRangeProcessing: boolean;
};

export type IFormFile = Blob | File;

export type NotificationResponse = {
  id: string;
  translatableTitleComponent: string;
  titleArguments: Array<string>;
  translatableBodyComponent: string;
  bodyArguments: Array<string>;
};

export type NumericMetricResponse = {
  value: number;
};

export type RecomendationTrend = 'Unknown' | 'Stable' | 'Increasing' | 'Decreasing';

export type RecommendationCollectionResponse = {
  total: number;
  results: Array<RecommendationResponse>;
};

export type RecommendationHistory = {
  firstOccurance: string;
  lastOccurance: string;
  averagePerDay: number;
  dailyOccurances: Array<DailyOccurance>;
  trend: RecomendationTrend;
};

export type RecommendationOrderBy = 'Importance' | 'MostRecentlyUpdated' | 'Url';

export type RecommendationResponse = {
  id: number;
  ignore: boolean;
  url: string;
  strategy: string;
  variableScore: number;
  updateDate: string;
  createDate: string;
};

export type RedactionScoreResponse = {
  key: string;
  score: number;
};

export type RedirectBulkRequest = {
  id: number;
  data: null | RedirectRequest;
};

export type RedirectCollectionResponse = {
  total: number;
  results: Array<RedirectResponse>;
};

export type RedirectRequest = {
  source: StrategyViewModel;
  target: StrategyViewModel;
  permanent: boolean;
  retainQuery: boolean;
  force: boolean;
  advanced: boolean;
};

export type RedirectResponse = {
  id: number;
  key: string;
  createDate: string;
  updateDate: string;
  additionalData: null | {
    [key: string]: unknown;
  };
  source: StrategyViewModel;
  target: StrategyViewModel;
  permanent: boolean;
  retainQuery: boolean;
  force: boolean;
  advanced: boolean;
};

export type RedirectType = string;

export type ReferrerResponse = {
  referrerOccurances: number;
  referrerUrl: string;
};

export type ScoreParametersResponse = {
  variableFactor: number;
  redactionFactor: number;
  timeFactor: number;
};

export type StrategyViewModel = {
  strategy: string;
  value: string;
};

export type Stream = Blob | File;

export type StringSegment = {
  buffer?: null | string;
  offset: number;
  length: number;
  value?: null | string;
  hasValue: boolean;
};

export type UpdateRecommendationRequest = {
  recommendationStrategy?: null | string;
  ignore?: null | boolean;
};

export type GetUrlTrackerLandingPageMetricData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/LandingPage/metric';
};

export type GetUrlTrackerLandingPageMetricErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUrlTrackerLandingPageMetricResponses = {
  /**
   * OK
   */
  200: NumericMetricResponse;
};

export type GetUrlTrackerLandingPageMetricResponse =
  GetUrlTrackerLandingPageMetricResponses[keyof GetUrlTrackerLandingPageMetricResponses];

export type GetUrlTrackerNotificationsByAliasData = {
  body?: never;
  path: {
    alias: string;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Notifications/{alias}';
};

export type GetUrlTrackerNotificationsByAliasErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUrlTrackerNotificationsByAliasResponses = {
  /**
   * OK
   */
  200: Array<NotificationResponse>;
};

export type GetUrlTrackerNotificationsByAliasResponse =
  GetUrlTrackerNotificationsByAliasResponses[keyof GetUrlTrackerNotificationsByAliasResponses];

export type GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryData = {
  body?: never;
  path: {
    recommendationId: number;
  };
  query?: {
    pastDays?: number;
  };
  url: '/umbraco/management/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/history';
};

export type GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses = {
  /**
   * OK
   */
  200: RecommendationHistory;
};

export type GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponse =
  GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses[keyof GetUrlTrackerRecommendationAnalysisByRecommendationIdHistoryResponses];

export type GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersData = {
  body?: never;
  path: {
    recommendationId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/RecommendationAnalysis/{recommendationId}/referrers';
};

export type GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses = {
  /**
   * OK
   */
  200: Array<ReferrerResponse>;
};

export type GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponse =
  GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses[keyof GetUrlTrackerRecommendationAnalysisByRecommendationIdReferrersResponses];

export type GetUrlTrackerRecommendationsData = {
  body?: never;
  path?: never;
  query?: {
    Query?: string;
    Types?: Array<string>;
    OrderBy?: RecommendationOrderBy;
    Desc?: boolean;
    Page?: number;
    PageSize?: number;
  };
  url: '/umbraco/management/api/v1/UrlTracker/Recommendations';
};

export type GetUrlTrackerRecommendationsErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUrlTrackerRecommendationsResponses = {
  /**
   * OK
   */
  200: RecommendationCollectionResponse;
};

export type GetUrlTrackerRecommendationsResponse =
  GetUrlTrackerRecommendationsResponses[keyof GetUrlTrackerRecommendationsResponses];

export type PostUrlTrackerRecommendationsByRecommendationIdData = {
  body: UpdateRecommendationRequest;
  path: {
    recommendationId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Recommendations/{recommendationId}';
};

export type PostUrlTrackerRecommendationsByRecommendationIdErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUrlTrackerRecommendationsByRecommendationIdResponses = {
  /**
   * OK
   */
  200: RecommendationResponse;
};

export type PostUrlTrackerRecommendationsByRecommendationIdResponse =
  PostUrlTrackerRecommendationsByRecommendationIdResponses[keyof PostUrlTrackerRecommendationsByRecommendationIdResponses];

export type PostUrlTrackerRecommendationsByRecommendationIdDeleteData = {
  body?: never;
  path: {
    recommendationId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Recommendations/{recommendationId}/delete';
};

export type PostUrlTrackerRecommendationsByRecommendationIdDeleteErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUrlTrackerRecommendationsByRecommendationIdDeleteResponses = {
  /**
   * OK
   */
  200: RecommendationResponse;
};

export type PostUrlTrackerRecommendationsByRecommendationIdDeleteResponse =
  PostUrlTrackerRecommendationsByRecommendationIdDeleteResponses[keyof PostUrlTrackerRecommendationsByRecommendationIdDeleteResponses];

export type PostUrlTrackerRecommendationsUpdatebulkData = {
  body: Array<EntityWithIdRequestOfUpdateRecommendationRequest>;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Recommendations/updatebulk';
};

export type PostUrlTrackerRecommendationsUpdatebulkErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUrlTrackerRecommendationsUpdatebulkResponses = {
  /**
   * OK
   */
  200: RecommendationResponse;
};

export type PostUrlTrackerRecommendationsUpdatebulkResponse =
  PostUrlTrackerRecommendationsUpdatebulkResponses[keyof PostUrlTrackerRecommendationsUpdatebulkResponses];

export type GetUrlTrackerScoringRedactionscoresData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Scoring/redactionscores';
};

export type GetUrlTrackerScoringRedactionscoresErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUrlTrackerScoringRedactionscoresResponses = {
  /**
   * OK
   */
  200: Array<RedactionScoreResponse>;
};

export type GetUrlTrackerScoringRedactionscoresResponse =
  GetUrlTrackerScoringRedactionscoresResponses[keyof GetUrlTrackerScoringRedactionscoresResponses];

export type GetUrlTrackerScoringScoreparametersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Scoring/scoreparameters';
};

export type GetUrlTrackerScoringScoreparametersErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUrlTrackerScoringScoreparametersResponses = {
  /**
   * OK
   */
  200: ScoreParametersResponse;
};

export type GetUrlTrackerScoringScoreparametersResponse =
  GetUrlTrackerScoringScoreparametersResponses[keyof GetUrlTrackerScoringScoreparametersResponses];

export type GetUrlTrackerRedirectImportExportData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/export';
};

export type GetUrlTrackerRedirectImportExportErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUrlTrackerRedirectImportExportResponses = {
  /**
   * OK
   */
  200: FileStreamResult;
};

export type GetUrlTrackerRedirectImportExportResponse =
  GetUrlTrackerRedirectImportExportResponses[keyof GetUrlTrackerRedirectImportExportResponses];

export type GetUrlTrackerRedirectImportExportexampleData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/exportexample';
};

export type GetUrlTrackerRedirectImportExportexampleErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUrlTrackerRedirectImportExportexampleResponses = {
  /**
   * OK
   */
  200: FileStreamResult;
};

export type GetUrlTrackerRedirectImportExportexampleResponse =
  GetUrlTrackerRedirectImportExportexampleResponses[keyof GetUrlTrackerRedirectImportExportexampleResponses];

export type PostUrlTrackerRedirectImportImportData = {
  body: {
    Redirects?: IFormFile;
  };
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/RedirectImport/import';
};

export type PostUrlTrackerRedirectImportImportErrors = {
  /**
   * Bad Request
   */
  400: unknown;
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type PostUrlTrackerRedirectImportImportResponses = {
  /**
   * OK
   */
  200: number;
};

export type PostUrlTrackerRedirectImportImportResponse =
  PostUrlTrackerRedirectImportImportResponses[keyof PostUrlTrackerRedirectImportImportResponses];

export type GetUrlTrackerRedirectsData = {
  body?: never;
  path?: never;
  query?: {
    Query?: string;
    Advanced?: boolean;
    Types?: Array<RedirectType>;
    SourceTypes?: Array<string>;
    Page?: number;
    PageSize?: number;
  };
  url: '/umbraco/management/api/v1/UrlTracker/Redirects';
};

export type GetUrlTrackerRedirectsErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetUrlTrackerRedirectsResponses = {
  /**
   * OK
   */
  200: RedirectCollectionResponse;
};

export type GetUrlTrackerRedirectsResponse = GetUrlTrackerRedirectsResponses[keyof GetUrlTrackerRedirectsResponses];

export type PostUrlTrackerRedirectsData = {
  body: CreateRedirectRequest;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects';
};

export type PostUrlTrackerRedirectsErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type PostUrlTrackerRedirectsResponses = {
  /**
   * OK
   */
  200: RedirectResponse;
};

export type PostUrlTrackerRedirectsResponse = PostUrlTrackerRedirectsResponses[keyof PostUrlTrackerRedirectsResponses];

export type GetUrlTrackerRedirectsByRedirectIdData = {
  body?: never;
  path: {
    redirectId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}';
};

export type GetUrlTrackerRedirectsByRedirectIdErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUrlTrackerRedirectsByRedirectIdResponses = {
  /**
   * OK
   */
  200: RedirectResponse;
};

export type GetUrlTrackerRedirectsByRedirectIdResponse =
  GetUrlTrackerRedirectsByRedirectIdResponses[keyof GetUrlTrackerRedirectsByRedirectIdResponses];

export type PostUrlTrackerRedirectsByRedirectIdData = {
  body: RedirectRequest;
  path: {
    redirectId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}';
};

export type PostUrlTrackerRedirectsByRedirectIdErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUrlTrackerRedirectsByRedirectIdResponses = {
  /**
   * OK
   */
  200: RedirectResponse;
};

export type PostUrlTrackerRedirectsByRedirectIdResponse =
  PostUrlTrackerRedirectsByRedirectIdResponses[keyof PostUrlTrackerRedirectsByRedirectIdResponses];

export type PostUrlTrackerRedirectsByRedirectIdDeleteData = {
  body?: never;
  path: {
    redirectId: number;
  };
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/{redirectId}/delete';
};

export type PostUrlTrackerRedirectsByRedirectIdDeleteErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUrlTrackerRedirectsByRedirectIdDeleteResponses = {
  /**
   * OK
   */
  200: RedirectResponse;
};

export type PostUrlTrackerRedirectsByRedirectIdDeleteResponse =
  PostUrlTrackerRedirectsByRedirectIdDeleteResponses[keyof PostUrlTrackerRedirectsByRedirectIdDeleteResponses];

export type PostUrlTrackerRedirectsDeletebulkData = {
  body: Array<number>;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/deletebulk';
};

export type PostUrlTrackerRedirectsDeletebulkErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUrlTrackerRedirectsDeletebulkResponses = {
  /**
   * No Content
   */
  204: void;
};

export type PostUrlTrackerRedirectsDeletebulkResponse =
  PostUrlTrackerRedirectsDeletebulkResponses[keyof PostUrlTrackerRedirectsDeletebulkResponses];

export type PostUrlTrackerRedirectsUpdatebulkData = {
  body: Array<RedirectBulkRequest>;
  path?: never;
  query?: never;
  url: '/umbraco/management/api/v1/UrlTracker/Redirects/updatebulk';
};

export type PostUrlTrackerRedirectsUpdatebulkErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type PostUrlTrackerRedirectsUpdatebulkResponses = {
  /**
   * OK
   */
  200: Array<RedirectResponse>;
};

export type PostUrlTrackerRedirectsUpdatebulkResponse =
  PostUrlTrackerRedirectsUpdatebulkResponses[keyof PostUrlTrackerRedirectsUpdatebulkResponses];

export type GetUrlTrackerRedirectTargetContentData = {
  body?: never;
  path?: never;
  query?: {
    Id?: string;
    Culture?: string;
  };
  url: '/umbraco/management/api/v1/UrlTracker/RedirectTarget/content';
};

export type GetUrlTrackerRedirectTargetContentErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
  /**
   * Not Found
   */
  404: unknown;
};

export type GetUrlTrackerRedirectTargetContentResponses = {
  /**
   * OK
   */
  200: ContentTargetResponse;
};

export type GetUrlTrackerRedirectTargetContentResponse =
  GetUrlTrackerRedirectTargetContentResponses[keyof GetUrlTrackerRedirectTargetContentResponses];
