<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Middleware</PackageId>
    <Title>URL Tracker Middleware</Title>
    <Description>This package contains middleware to perform redirects and to register client errors with the URL Tracker</Description>
    <RootNamespace>UrlTracker.Middleware</RootNamespace>
    <PackageReleaseNotes>4 new features, 3 other changes

- Add recommendation analytics
- Add classification mechanics
- Add scoring mechanics
- Add cleanup routines
- Improve user experience
- Improve dashboard performance
- New design that is more umbraco-like</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Core" Version="10.6.1" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="10.6.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Core\UrlTracker.Core.csproj" />
    <ProjectReference Include="..\UrlTracker.Modules\UrlTracker.Modules.csproj" />
    <ProjectReference Include="..\UrlTracker.Web\UrlTracker.Web.csproj" />
  </ItemGroup>
</Project>