<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>UrlTracker.Middleware</PackageId>
    <Title>URL Tracker Middleware</Title>
    <Description>This package contains middleware to perform redirects and to register client errors with the URL Tracker</Description>
    <RootNamespace>UrlTracker.Middleware</RootNamespace>
    <PackageReleaseNotes>1 new feature, 1 bugfix, 1 other change

- Fix stale caches on load balanced environments
- (Experimental) Add active cache
- Optimise database query performance</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Core" Version="10.6.1" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="10.6.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlTracker.Core\UrlTracker.Core.csproj" />
    <ProjectReference Include="..\UrlTracker.Modules\UrlTracker.Modules.csproj" />
    <ProjectReference Include="..\UrlTracker.Web\UrlTracker.Web.csproj" />
  </ItemGroup>
</Project>